services:

  api:
    build:
      context: ./services/api
    ports:
      - "4000:4000"
    volumes:
      - ./services/api:/app
    restart: always

  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4000
    depends_on:
      - api
    restart: always